name: 'crypto_dbt'
version: '1.0.0'
config-version: 2

profile: 'crypto_dbt'

model-paths: ["models"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  crypto_dbt:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: analytics
      +materialized: table